### ISSUE TITLE
list trunk - Termination not fount - line 205

### ISSUE THREAD

**Issue by haljus** [deesnow/ossi_tool#15]
Hello,

When I issue list trunk at the screen I have "Termination not fount - line 205"
At the csv file I dont see this info. Looks good at the file.

-------- 
list trunk-group
--------
**Termination not fount - line 205**
1,#001,isdn,PSTN/Building1 I/TFN,46,1,90,y,both,n,0
2,#002,isdn,PSTN/Building2 I/O FAX-MODEM,69,1,90,y,ext,n,0

**Comment by deesnow** [comment]
@haljus
which version do you use?

I just released new 0.4rc3 and set proper timeout for 'list trunk' command. It should be OK.
pls update with 'pip install --upgrade --pre ossi-tool'

**Comment by haljus** [comment]
I am on ossi-tool-0.4rc2

**Comment by haljus** [comment]
Just updated:
Successfully installed ossi-tool-0.4rc3 pexpect-4.8.0 ptyprocess-0.6.0

**Comment by deesnow** [comment]
Fixed.
