### ISSUE TITLE
List station - fields not aligned

### ISSUE THREAD

**Issue by haljus** [deesnow/ossi_tool#16]
Hi,

Fields on list station are not in the same order,
Below is the command issued from SAT and the output on csv file

![image](https://user-images.githubusercontent.com/64594264/80722165-b13cdb00-8ac4-11ea-8af8-c32521e0c7b8.png)

list station                                                           Page   1

                                  STATIONS

Ext/          Port/   Name/                       Room/         Cv1/ COR/ Cable/
 Hunt-to       Type      Surv GK NN        Move    Data Ext      Cv2  COS  Jack

100         S28861  ~~avaya test1                                   1
               9620                        no                         1
104         X       ~~avaya test2                 278314            31   C1N27
               6408D+                      no                         1

**Result:**

100,S28861,~~avaya test1,1,,,9620,no,,,1
104,X,~~avaya test2,278314,31,C1N27,,6408D+,no,,,1

**Comment by deesnow** [comment]
Could you run the command with -v option and attached here the debug.log
Dont forget to remove the password from the log file ;)

**Comment by haljus** [comment]
Does it work if I send just the code for those 2 extensions mentioned in the example?
check below

clist station ext 100 to-ext 110
t
clist station ext 100 to-ext 110

t

clist station ext 100 to-ext 110

f8005ff00	8004ff00	8003ff00	0031ff00	8007ff00

f8001ff00	0033ff00	4e22ff00	004fff00	700dff00

f6a01ff00	0019ff00	ce2aff00	8002ff00	0032ff00

d100	S28861	~~avaya test1		

d1			9620	

dno			1	

n

d104	X	~~avaya test2	278314	

d31	C1N27		6408D+	

dno			1	

n

**I see that the below should be:**
8005ff00 - Extension
8004ff00 - Port
8003ff00 - Name
0031ff00 - Room
8007ff00 - Coverage_Path_1

But for some reason the system is not adding "," if the return is null

**Comment by deesnow** [comment]
Yes... there are 15 fields (3x 5)

![image](https://user-images.githubusercontent.com/8372254/80736438-6e095900-8b12-11ea-88f7-eb9ab314f50a.png)

All field are separated by Tab and it seems my parser function remove it with the carriage return + line feed characters. I will change the behavior of that part.

Thx for your feedback ;)

**Comment by deesnow** [comment]
fixed in 0.4rc4
