### ISSUE TITLE
Some values not separated by commas

### ISSUE THREAD

**Issue by drkfhr** [deesnow/ossi_tool#3]
LOVE the ossi_tool!  

Having issues with some reports though, for example list registered to return a list of registered ip stations and the details associated with them.  The IP address and network region are concatenated together, as are some other fields on this report, and other reports.  Here's an example of the output:

3013,9650,oneX_Comm,y,10.79.3.97102,2.000,10.65.137.43,,30139650,,n,0.0.0.0,0,0.0.0.0,3013,9650,n,0.0.0.0,0,,0.0.0.0

the IP address and network region appear as "10.79.3.97102" where it should be "10.79.3.97,102", and the extension and set type are also concatenated here.  "30139650" should be "3013,9650"

Thank you for creating this tool!

**Comment by deesnow** [comment]
Hi,
It was just a "learning" project of python, but happy to hear it is useful. Unfortunately I have very limited time nowadays so cannot promise it will be fixed soon, but try to fix it.

**Comment by drkfhr** [comment]
Hi Janos,

Thanks for the reply!  Actually, I made some customizations to your code
(I'm just learning Python now) and got it to a state where I can use it in
my project.  I'm working on a set of cron jobs that automatically pulls a
set of reports (list registered, list extension, list agents, list ars,
etc) and pushes the data into an MSSQL database where it's used by a series
of web pages I've written over the years (company directory, DID
management, etc.)

Thank you for sharing this and replying to my query!

**Comment by Alkaceq** [comment]
Hello deesnow, I would like to appreciate your ossi_tool project as well. Good work, I'm also using it, even my python knowledge is fairly limited

The same problem appears in "mon tra tru" command, where coma is missing inbetween 0 and 10
11:38 SUN SEP 15 2019,1    30   5    0    0,2    30   0    0    0,3    30   0    0    0,5    60   2    0    010   10   0    0    0,22   10   0    0    0,23   5    0    0    0 

sharing just in case you would manage to find some time. Cheers, Marcus

**Comment by deesnow** [comment]
> LOVE the ossi_tool!
> 
> Having issues with some reports though, for example list registered to return a list of registered ip stations and the details associated with them. The IP address and network region are concatenated together, as are some other fields on this report, and other reports. Here's an example of the output:
> 
> 3013,9650,oneX_Comm,y,10.79.3.97102,2.000,10.65.137.43,,30139650,,n,0.0.0.0,0,0.0.0.0,3013,9650,n,0.0.0.0,0,,0.0.0.0
> 
> the IP address and network region appear as "10.79.3.97102" where it should be "10.79.3.97,102", and the extension and set type are also concatenated here. "30139650" should be "3013,9650"
> 
> Thank you for creating this tool!

@drkfhr ,
I have reviewd and re-write the data_parser, so it seems it fixed your problem. Upgrade your package with pip. Let me know if it is works properly. If not then pleas start your scrip with -v and send me the debug.log.

**Comment by deesnow** [comment]
> Hello deesnow, I would like to appreciate your ossi_tool project as well. Good work, I'm also using it, even my python knowledge is fairly limited
> 
> The same problem appears in "mon tra tru" command, where coma is missing inbetween 0 and 10
> 11:38 SUN SEP 15 2019,1 30 5 0 0,2 30 0 0 0,3 30 0 0 0,5 60 2 0 010 10 0 0 0,22 10 0 0 0,23 5 0 0 0
> 
> sharing just in case you would manage to find some time. Cheers, Marcus

@Alkaceq 
Packaged is updated, so you can retest it. The output for this command a bit different, because not the fieds, but the trunks are separated by coma. If it is not useful, than have to apply command based output parsing.

**Comment by drkfhr** [comment]
That's great!! Thank you!  I'll apply the fix and try it out.

I have to admit though, I made some modifications myself, and implemented a
framework using shell scripts and cron so it pulls data from my switch at
scheduled intervals and stuffs it in to a MSSQL server.  Let me know if
you're interested and I can share it with you.

Thanks,
Derek

**Comment by deesnow** [comment]
I have completely changed the command output parsing to have common rules and avoid different behavior for different commands.

**Comment by Alkaceq** [comment]
Thank you!! Fantastic, I have tested the updated version and can confirm its working, the comas are whey they suppose to be.  I appreciate your time.
