### ISSUE TITLE
Timeout issue - -t not works as expected

### ISSUE THREAD

**Issue by deesnow** [deesnow/ossi_tool#8]
Also please test -t with many lines of some command in Input.csv file. In my case there is no any timeout even if I put   -t 2   for 2 seconds; terminal lines scroll very fast and some commands are failed.
Without -t it works fine with 2 seconds timeout.
Thank you!

_Originally posted by @fiodorpugach in https://github.com/deesnow/ossi_tool/issues/6#issuecomment-610427922_

**Comment by fiodorpugach** [comment]
I just tested with 3 lines of 'list bridg xxxxx'
Lines scrolled fast with -t 2 and one line was failed:

fiodor@MM247321-PC:~$ ossi_tool 129.83.44.251 ossitool -pXXXXXX -i Input.csv -o Output.csv -t 2 -v
--- Let Start! ---
--- Connection established ---
--- Ossi is logged in and ready ---
 -- Input.csv is opened --
--------
list  bridg  77703
--------



--------
list  bridg  77704
--------
-- Command Error --



--------
list  bridg  77705
--------
77707,1  2


--- Ossi logged out ---
*** 1 commands are failed ***
*** End of Errors ***
--- Script running is finished ---
fiodor@MM247321-PC:~$

**Comment by fiodorpugach** [comment]
[debug.log](https://github.com/deesnow/ossi_tool/files/4466374/debug.log)

**Comment by fiodorpugach** [comment]
-t still does not work correctly with new ossit.py and ossit.pyc files. But I made manual changes in ossit.py and now it works good for me. I changed line 67 to self.timeout = 0.3 and added line before line 194: self.s.timeout = 0.3

**Comment by deesnow** [comment]
> -t still does not work correctly with new ossit.py and ossit.pyc files. But I made manual changes in ossit.py and now it works good for me. I changed line 67 to self.timeout = 0.3 and added line before line 194: self.s.timeout = 0.3

That way the 0.3 is hardcoded.
But if add  timeout=self.timeout to all self.s.expect than it will get the value from the -t parameter.
like this:
`self.index = self.s.expect(['\rmore..y.', 'e1.*', 'f.*'], timeout=self.timeout)`


I'm going to fix it and release it.

**Comment by deesnow** [comment]
I have released a new release candidate version. In that version I completely removed the -t parameter, because a new approach is applied to match the prompt faster, so not necessary set timeout manually. There is new file which contains long running commands and its timeout, others will use the default 0.2 sec. In case of no match the timeout automatically increased.

In my environment I have done many testes, will be great if we have more.

You can download the new version from here https://github.com/deesnow/ossi_tool/tree/version-1 or update your package with pip to 0.4rc1
`sudo pip install --upgrade --pre ossi-tool`
